function Q = IK(p_0T, kin)

    [Q_1, Q_2, Q_3] = subproblem.sp_5(...
        -kin.P(:,2),...
        p_0T - kin.P(:,1),...
        kin.P(:,3),...
        kin.P(:,4),...
        -kin.H(:,1), kin.H(:,2), kin.H(:,3));
    Q = [Q_1; Q_2; Q_3];
end